config/routes.rb
Rails.application.routes.draw do
  resource :schedule
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  devise_for :users

  root to: "schedules#show"
end

app/models/concert.rb
# == Schema Information
#
# Table name: concerts
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  start_time  :datetime
#  venue_id    :bigint(8)
#  genre_tags  :text
#  ilk         :integer
#  access      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Concert < ApplicationRecord
  belongs_to :venue
  has_many :gigs, -> { order(order: :asc) }, dependent: :destroy
  has_many :bands, through: :gigs

  enum ilk: %i[concert meet-n-greet battle]
  enum access: %i[general members vips]

  def start_day
    start_time.to_date
  end

  def duration_minutes
    gigs.map(&:duration_minutes).sum
  end

  def genre_parameters
    genre_tags.split(",").map(&:parameterize).join(",")
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_concert
    @concert = Concert.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def concert_params
    params.require(:concert).permit(:name, :description, :start_time, :venue_id, :genre_tags, :ilk, :access)
  end
end

app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.text_field :venue_id %>
  </div>

  <div class="field">
    <%= form.label :genre_tags %>
    <%= form.text_area :genre_tags %>
  </div>

  <div class="field">
    <%= form.label :ilk %>
    <%= form.number_field :ilk %>
  </div>

  <div class="field">
    <%= form.label :access %>
    <%= form.number_field :access %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render "form", concert: @concert %>

<%= link_to "Show", @concert %> |
<%= link_to "Back", concerts_path %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>Venue</th>
      <th>Genre tags</th>
      <th>Ilk</th>
      <th>Access</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.name %></td>
        <td><%= concert.description %></td>
        <td><%= concert.start_time %></td>
        <td><%= concert.venue_id %></td>
        <td><%= concert.genre_tags %></td>
        <td><%= concert.ilk %></td>
        <td><%= concert.access %></td>
        <td><%= link_to "Show", concert %></td>
        <td><%= link_to "Edit", edit_concert_path(concert) %></td>
        <td><%= link_to "Destroy", concert, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to "New Concert", new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render "form", concert: @concert %>

<%= link_to "Back", concerts_path %>

app/views/concerts/show.html.erb
<h1 class="title is-size-1"><%= @concert.name %></h1>

<h2 class="subtitle is-size-2">Ticket Info</h2>

<h3 class="is-size-3"><%= @concert.ilk %></h3>
<h3 class="is-size-3"><%= @concert.access %></h3>

<h3 class="is-size-3">
  Start Date: &nbsp;
  <%= @concert.start_time.by_example("Jan 02, 2006") %>
</h3>

<h3 class="is-size-3">Venue: <%= @concert.venue.name %></h3>

<h3 class="is-size-3">Schedule:</h3>
<% running_time = @concert.start_time %>
<table class="table">
  <thead>
    <tr>
      <th>Time</th>
      <th>Band</th>
      <th>Genres</th>
    </tr>
  </thead>
  <tbody>
    <% @concert.gigs.each do |gig| %>
      <tr>
        <td><%= running_time.by_example("03:04 PM") %></td>
        <td><%= gig.band.name %></td>
        <td><%= gig.band.genre_tags %></td>
      <% running_time += (gig.duration_minutes * 60) %>
      </tr>
    <% end %>
  </tbody>
</table>

<h2 class="is-size-2">Tickets</h2>

<table class="table">
  <tbody>
    <% @concert.venue.rows.times do %>
      <tr>
        <% @concert.venue.seats_per_row.times do %>
          <td>
            <div class="icon">
              <i class="far fa-square"></i>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="actions">
  <%= link_to("Edit", edit_concert_path(@concert)) %>
  |
  <%= link_to("Back", concerts_path) %>
</div>