config/routes.rb
Rails.application.routes.draw do
  resource :schedule
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  devise_for :users

  root to: "schedules#show"
end

app/models/ticket_order.rb
# == Schema Information
#
# Table name: ticket_orders
#
#  id         :bigint(8)        not null, primary key
#  gig_id     :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TicketOrder < ApplicationRecord
  belongs_to :gig
end

app/controllers/ticket_orders_controller.rb
class TicketOrdersController < ApplicationController
  before_action :set_ticket_order, only: [:show, :edit, :update, :destroy]

  # GET /ticket_orders
  # GET /ticket_orders.json
  def index
    @ticket_orders = TicketOrder.all
  end

  # GET /ticket_orders/1
  # GET /ticket_orders/1.json
  def show
  end

  # GET /ticket_orders/new
  def new
    @ticket_order = TicketOrder.new
  end

  # GET /ticket_orders/1/edit
  def edit
  end

  # POST /ticket_orders
  # POST /ticket_orders.json
  def create
    @ticket_order = TicketOrder.new(ticket_order_params)

    respond_to do |format|
      if @ticket_order.save
        format.html { redirect_to @ticket_order, notice: "Ticket order was successfully created." }
        format.json { render :show, status: :created, location: @ticket_order }
      else
        format.html { render :new }
        format.json { render json: @ticket_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_orders/1
  # PATCH/PUT /ticket_orders/1.json
  def update
    respond_to do |format|
      if @ticket_order.update(ticket_order_params)
        format.html { redirect_to @ticket_order, notice: "Ticket order was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket_order }
      else
        format.html { render :edit }
        format.json { render json: @ticket_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_orders/1
  # DELETE /ticket_orders/1.json
  def destroy
    @ticket_order.destroy
    respond_to do |format|
      format.html { redirect_to ticket_orders_url, notice: "Ticket order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket_order
    @ticket_order = TicketOrder.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_order_params
    params.require(:ticket_order).permit(:gig_id)
  end
end

app/views/ticket_orders/_form.html.erb
<%= form_with(model: ticket_order, local: true) do |form| %>
  <% if ticket_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_order.errors.count, "error") %> prohibited this ticket_order from being saved:</h2>

      <ul>
      <% ticket_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :gig_id %>
    <%= form.text_field :gig_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ticket_orders/edit.html.erb
<h1>Editing Ticket Order</h1>

<%= render "form", ticket_order: @ticket_order %>

<%= link_to "Show", @ticket_order %> |
<%= link_to "Back", ticket_orders_path %>

app/views/ticket_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ticket Orders</h1>

<table>
  <thead>
    <tr>
      <th>Gig</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_orders.each do |ticket_order| %>
      <tr>
        <td><%= ticket_order.gig_id %></td>
        <td><%= link_to "Show", ticket_order %></td>
        <td><%= link_to "Edit", edit_ticket_order_path(ticket_order) %></td>
        <td><%= link_to "Destroy", ticket_order, method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to "New Ticket Order", new_ticket_order_path %>

app/views/ticket_orders/new.html.erb
<h1>New Ticket Order</h1>

<%= render "form", ticket_order: @ticket_order %>

<%= link_to "Back", ticket_orders_path %>

app/views/ticket_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gig:</strong>
  <%= @ticket_order.gig_id %>
</p>

<%= link_to "Edit", edit_ticket_order_path(@ticket_order) %> |
<%= link_to "Back", ticket_orders_path %>